# Generated by Django 5.2.14 on 2026-05-06 11:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readwise_id', models.BigIntegerField(db_index=True, unique=True)),
                ('text', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('source_title', models.CharField(blank=True, default='', max_length=512)),
                ('source_author', models.CharField(blank=True, default='', max_length=256)),
                ('source_url', models.URLField(blank=True, default='', max_length=1024)),
                ('tags', models.JSONField(default=list)),
                ('highlighted_at', models.DateTimeField(blank=True, null=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-highlighted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cursor_used', models.CharField(blank=True, default='', max_length=512)),
                ('next_cursor', models.CharField(blank=True, default='', max_length=512)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('highlights', models.ManyToManyField(related_name='classification_batches', to='wiki.highlight')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('highlight_count_at_last_summary', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_topics', models.ManyToManyField(blank=True, to='wiki.topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='highlight',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='wiki.topic'),
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('classify', 'Classify highlights'), ('summarize', 'Summarize topic')], max_length=32)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_estimate_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='wiki.classificationbatch')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='wiki.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', '-created_at'], name='wiki_llmcal_purpose_819c21_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['topic', '-highlighted_at'], name='wiki_highli_topic_i_613e06_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['classified_at'], name='wiki_highli_classif_eaed18_idx'),
        ),
    ]
